#Ansible Managed
global:
  smtp_smarthost: 'email.amazonaws.com:587'
  smtp_from: 'admin@prometheus.example.com'
  smtp_auth_username: 'AAAAAAAAAAAAAAAAA'
  smtp_auth_password: 'Aeeeeeeeeeeeeeeeeeeeeeee'
templates: 
- '/etc/alertmanager/template/*.tmpl'
route:
  group_by: ['name']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h 
  # A default receiver
  receiver: first-level-notifiers 
  routes:
receivers:
- name: 'first-level-notifiers'
  email_configs:
  - to: 'unnisathya88@gmail.com'
    send_resolved: true
  slack_configs:
  - api_url: https://hooks.slack.com/services/Teeeeeeeeeeeeeeeeeeeeeeee7
    send_resolved: true
    channel: '#prometheus-alerts'

